package currency

import (
	"embed"
	"encoding/json"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/pkg/errors"
	"golang.org/x/text/language"
)

//go:embed sources/currencyData.json sources/likelySubtags.json sources/currencyNames.json
var cldrDataset embed.FS

type supplementalVersion struct {
	UnicodeVersion string `json:"_unicodeVersion"`
	CLDRVersion    string `json:"_cldrVersion"`
}

type supplementalCurrencyData struct {
	Supplemental struct {
		Version      supplementalVersion `json:"version"`
		CurrencyData struct {
			Fractions map[string]supplementalCurrencyFraction            `json:"fractions"`
			Region    map[string][]map[string]supplementalCurrencyRegion `json:"region"`
		} `json:"currencyData"`
	} `json:"supplemental"`
}

type supplementalCurrencyFraction struct {
	Rounding     string `json:"_rounding"`
	Digits       string `json:"_digits"`
	CashRounding string `json:"_cashRounding"`
	CashDigits   string `json:"_cashDigits"`
}

type supplementalCurrencyRegion struct {
	From   *jsonDate `json:"_from"`
	To     *jsonDate `json:"_to"`
	Tender *string   `json:"_tender"`
}

// isCurrent returns true if the currency is still in use in the region and is
// legal tender.
func (s supplementalCurrencyRegion) isCurrent() bool {
	return s.To == nil && (s.Tender == nil || *s.Tender != "false")
}

type supplementalLikelySubtags struct {
	Supplemental struct {
		LikelySubtags map[string]string `json:"likelySubtags"`
	} `json:"supplemental"`
}

// currencyLocaleData is the format of the currencyNames.json file generated by
// cldrgen. Blank fields are inherited from the parent locale.
type currencyLocaleData struct {
	Name   string `json:"n,omitempty"`
	Symbol string `json:"s,omitempty"`
}

type jsonDate time.Time

func (j *jsonDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(time.Time(*j).Format(time.DateOnly))
}

func (j *jsonDate) UnmarshalJSON(input []byte) error {
	inputStr := string(input)
	// Need to remove leading and trailing double quotes too.
	inputStr = strings.Trim(inputStr, `"`)
	result, err := time.Parse(time.DateOnly, inputStr)
	if err != nil {
		return err
	}
	*j = jsonDate(result)
	return nil
}

var (
	cldrVersion string
	// currencies is the sorted list of currency codes that are currently legal
	// tender in at least one region.
	currencies []string
	// fractionalDigits is keyed by currency code and contains the number of
	// digits after the decimal place for that currency. Only currencies that are
	// in the currencies list will be present.
	fractionalDigits map[string]int64
	// regionCurrencies is keyed by the region code (like US) and contains the
	// currency that is currently legal tender for that region.
	regionCurrencies map[string]string
	// likelySubtags maps a partial locale (like "en" or "und_DE") to the most
	// likely full locale (like "en-Latn-US" or "de-Latn-DE").
	likelySubtags map[string]string
	// currencyNames is keyed by the CLDR locale (like "de-CH") and then by the
	// currency code. A locale only contains the values that differ from its
	// parent locale.
	currencyNames map[string]map[string]currencyLocaleData
	// locales is the list of CLDR locales that currency names are available for,
	// in the same order as the tags given to localeMatcher.
	locales       []string
	localeMatcher language.Matcher
)

// defaultLocale is used when the requested locale does not match anything
// that CLDR has data for.
const defaultLocale = "en"

func init() {
	if err := loadCLDR(); err != nil {
		panic(fmt.Sprintf("failed to load embedded CLDR dataset: %+v", err))
	}
}

func loadCLDR() error {
	var currencyData supplementalCurrencyData
	if err := readCLDRFile("sources/currencyData.json", &currencyData); err != nil {
		return err
	}
	var subtags supplementalLikelySubtags
	if err := readCLDRFile("sources/likelySubtags.json", &subtags); err != nil {
		return err
	}

	data := currencyData.Supplemental.CurrencyData
	// Currencies not listed in the fractions map use the DEFAULT entry.
	defaultDigits, err := strconv.ParseInt(data.Fractions["DEFAULT"].Digits, 10, 64)
	if err != nil {
		return errors.Wrap(err, "failed to parse default currency digits")
	}

	fractionalDigits = map[string]int64{}
	regionCurrencies = map[string]string{}
	for region, entries := range data.Region {
		for _, entry := range entries {
			for code, details := range entry {
				if !details.isCurrent() {
					continue
				}

				// Regions list their current currencies first, so the first current
				// currency we see is the primary one for that region.
				if _, ok := regionCurrencies[region]; !ok {
					regionCurrencies[region] = code
				}

				if _, ok := fractionalDigits[code]; ok {
					continue
				}
				digits := defaultDigits
				if fraction, ok := data.Fractions[code]; ok {
					digits, err = strconv.ParseInt(fraction.Digits, 10, 64)
					if err != nil {
						return errors.Wrapf(err, "failed to parse digits for currency [%s]", code)
					}
				}
				fractionalDigits[code] = digits
			}
		}
	}

	currencies = make([]string, 0, len(fractionalDigits))
	for code := range fractionalDigits {
		currencies = append(currencies, code)
	}
	slices.Sort(currencies)

	if err := readCLDRFile("sources/currencyNames.json", &currencyNames); err != nil {
		return err
	}
	if _, ok := currencyNames[defaultLocale]; !ok {
		return errors.Errorf("default locale [%s] is missing from currency names", defaultLocale)
	}
	// The first tag given to the matcher is used as the fallback when nothing
	// else matches, so the default locale must be first.
	locales = []string{defaultLocale}
	for locale := range currencyNames {
		if locale != defaultLocale {
			locales = append(locales, locale)
		}
	}
	slices.Sort(locales[1:])
	tags := make([]language.Tag, 0, len(locales))
	for _, locale := range locales {
		tag, err := language.Parse(locale)
		if err != nil {
			return errors.Wrapf(err, "failed to parse CLDR locale [%s]", locale)
		}
		tags = append(tags, tag)
	}
	localeMatcher = language.NewMatcher(tags)

	cldrVersion = currencyData.Supplemental.Version.CLDRVersion
	likelySubtags = subtags.Supplemental.LikelySubtags
	return nil
}

func readCLDRFile(path string, result any) error {
	file, err := cldrDataset.Open(path)
	if err != nil {
		return errors.Wrapf(err, "failed to open CLDR file [%s]", path)
	}
	defer file.Close()
	if err := json.NewDecoder(file).Decode(result); err != nil {
		return errors.Wrapf(err, "failed to parse CLDR file [%s]", path)
	}
	return nil
}

// GetCLDRVersion returns the version of the CLDR dataset embedded in monetr.
func GetCLDRVersion() string {
	return cldrVersion
}

// GetCurrencies returns a sorted list of all of the ISO 4217 currency codes
// that monetr supports. The returned slice is a copy and can be modified.
func GetCurrencies() []string {
	return slices.Clone(currencies)
}

// IsSupportedCurrency returns true if the provided currency code is one that
// monetr supports.
func IsSupportedCurrency(currency string) bool {
	_, ok := fractionalDigits[currency]
	return ok
}

// GetFractionalDigits returns the number of digits after the decimal place
// that the provided currency uses. For example USD uses 2 and JPY uses 0.
func GetFractionalDigits(currency string) (int64, error) {
	digits, ok := fractionalDigits[currency]
	if !ok {
		return 0, errors.New("currency not supported")
	}
	return digits, nil
}

// GetCurrencyForLocale returns the currency that is currently legal tender in
// the region for the provided locale. The locale can be in either BCP 47 form
// like "en-US" or in POSIX form like "en_US.UTF-8". If the locale does not
// include a region then the most likely region for the language is used, for
// example "ja" will resolve to JPY.
func GetCurrencyForLocale(locale string) (string, error) {
	region, err := getRegionForLocale(locale)
	if err != nil {
		return "", err
	}
	code, ok := regionCurrencies[region]
	if !ok {
		return "", errors.Errorf("no currency found for locale [%s] region [%s]", locale, region)
	}
	return code, nil
}

func getRegionForLocale(locale string) (string, error) {
	// Strip any POSIX encoding or modifier, like en_US.UTF-8 or de_DE@euro.
	if i := strings.IndexAny(locale, ".@"); i >= 0 {
		locale = locale[:i]
	}
	parts := strings.FieldsFunc(locale, func(r rune) bool {
		return r == '_' || r == '-'
	})
	if len(parts) == 0 {
		return "", errors.New("locale cannot be blank")
	}

	// If the locale includes a region then use that. Regions are either two
	// letters or three digits, scripts (like Latn) are four letters and are
	// skipped.
	for _, part := range parts[1:] {
		if isRegionSubtag(part) {
			return strings.ToUpper(part), nil
		}
	}

	// Otherwise derive the most likely region from the language.
	language := strings.ToLower(parts[0])
	likely, ok := likelySubtags[language]
	if !ok {
		return "", errors.Errorf("unknown language for locale [%s]", locale)
	}
	for _, part := range strings.Split(likely, "-")[1:] {
		if isRegionSubtag(part) {
			return part, nil
		}
	}
	return "", errors.Errorf("could not determine region for locale [%s]", locale)
}

func isRegionSubtag(part string) bool {
	switch len(part) {
	case 2:
		return isAll(part, func(r rune) bool {
			return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
		})
	case 3:
		return isAll(part, func(r rune) bool { return r >= '0' && r <= '9' })
	default:
		return false
	}
}

func isAll(input string, predicate func(r rune) bool) bool {
	for _, r := range input {
		if !predicate(r) {
			return false
		}
	}
	return true
}

// MatchLocale takes the value of an Accept-Language header and returns the
// closest locale that monetr has currency names for. If nothing matches, or
// the header is blank or invalid, then the default locale (en) is returned.
func MatchLocale(acceptLanguage string) string {
	tags, _, err := language.ParseAcceptLanguage(acceptLanguage)
	if err != nil || len(tags) == 0 {
		return defaultLocale
	}
	_, index, _ := localeMatcher.Match(tags...)
	return locales[index]
}

// GetCurrency returns the details of a single currency with its name and
// symbol localized for the provided locale. The locale should be one returned
// by [MatchLocale].
func GetCurrency(locale, code string) (Currency, error) {
	digits, err := GetFractionalDigits(code)
	if err != nil {
		return Currency{}, err
	}

	result := Currency{
		Code:             code,
		FractionalDigits: digits,
	}
	// Walk up from the requested locale through its parents, then fall back to
	// the default locale, taking the first value we find for each field.
	for _, candidate := range append(localeChain(locale), defaultLocale) {
		data := currencyNames[candidate][code]
		if result.Name == "" {
			result.Name = data.Name
		}
		if result.Symbol == "" {
			result.Symbol = data.Symbol
		}
		if result.Name != "" && result.Symbol != "" {
			break
		}
	}
	// If CLDR has nothing at all then the code is the best we can do.
	if result.Name == "" {
		result.Name = code
	}
	if result.Symbol == "" {
		result.Symbol = code
	}
	return result, nil
}

// GetCurrencyList returns the details of every supported currency, sorted by
// currency code, with names and symbols localized for the provided locale.
func GetCurrencyList(locale string) []Currency {
	result := make([]Currency, 0, len(currencies))
	for _, code := range currencies {
		// Every code in currencies is supported so this cannot fail.
		item, _ := GetCurrency(locale, code)
		result = append(result, item)
	}
	return result
}

// localeChain returns the locale followed by each of its parents, truncating
// one subtag at a time. So zh-Hant-TW returns zh-Hant-TW, zh-Hant, zh. This
// must match the parent logic in cldrgen.
func localeChain(locale string) []string {
	chain := []string{locale}
	for {
		i := strings.LastIndex(locale, "-")
		if i < 0 {
			return chain
		}
		locale = locale[:i]
		chain = append(chain, locale)
	}
}
