package swag

import "time"

type AlwaysTransaction struct {
	// The amount of the transaction in cents. This is used when a transaction is "spent-from" a spending object.Validate
	//
	// **NOTE**: `amount` cannot be updated on transactions that were created from Plaid.
	Amount int64 `json:"amount" validate:"required" minimum:"1"`
	// The expense or goal's spending Id that this transaction was spent from. When this is updated the spending amount
	// will also be updated here. On the spending object the allocated amount will be subtracted from up to the amount
	// of this transaction. But the spending objects allocated amount will never be negative. If you have a transaction
	// that is $10.00 and you spend it from a spending object with only $8.00 allocated, then only $8.00 will be
	// subtracted from the spending object. Those $8.00 will be represented by the `spendingAmount` field here.
	SpendingId *uint64 `json:"spendingId" example:"54312" extensions:"x-nullable"`
	// Represents a path of categories that represents what type of spending this transaction was. For example:
	// `["Restaurants", "Fast Food"]`. A transaction could just have the category of `Restaurants`, but it can have a
	// child category of `Fast Food` as well. This field can be maintained directly by the end user. But is typically
	// generated when the transaction is created from Plaid.
	Categories []string `json:"categories" example:"Restaurants,Fast Food" extensions:"x-nullable"`
	// Date is the date the transaction was created. This date cannot change on this particular transaction Id, but if
	// the transaction is in a `Pending` state then when the transaction clears a new transaction can be created and
	// this transaction would be deleted. This can change the `date` field when this occurs.
	//
	// **NOTE**: `date` cannot be updated on transactions that were created from Plaid.
	Date time.Time `json:"date" example:"2021-04-15T00:00:00-05:00"`
	// Authorized date comes from Plaid, but to my knowledge will not be populated in this API until we support UK
	// banks.
	// > This field is only populated for UK institutions. For institutions in other countries, will be null.
	//
	// https://plaid.com/docs/api/products/#transactions-get-response-authorized-datetime_transactions
	//
	// **NOTE**: `authorizedDate` cannot be updated on transactions that were created from Plaid.
	AuthorizedDate *time.Time `json:"authorizedDate" extensions:"x-nullable"`
	// The transaction name that the user has customized, or that has been generated by monetr when the transaction was
	// imported from Plaid.
	Name string `json:"name,omitempty"`
	// The merchant name that was specified by the user, or was imported with the transaction's data from Plaid.
	MerchantName string `json:"merchantName,omitempty"`
	// Indicates whether or not the transaction is pending. Pending transactions are deleted when they clear their
	// pending status and if the transaction completes, a new transaction with a non-pending status is created. If the
	// transaction clears its pending status but is not complete (refunded), then it is simply deleted. This is only
	// the case with Plaid transactions, manual transactions can be updated between pending and non-pending in place.
	//
	// **NOTE**: `isPending` cannot be updated on transactions that were created from Plaid.
	IsPending bool `json:"isPending" example:"true"`
}

type UpdateTransactionRequest struct {
	AlwaysTransaction
}

type NewTransactionRequest struct {
	AlwaysTransaction

	// The Id of bank account that this transaction is associated with. A transaction can only be associated with a
	// single bank account. It is required when creating a new transaction.
	BankAccountId uint64 `json:"bankAccountId" example:"43872" validate:"required"`
	// The original name of the transaction when it was created. This is the name specified when the user manually
	// created the transaction, or when the transaction was imported from Plaid. This field cannot be changed after the
	// transaction is created.
	OriginalName string `json:"originalName" example:"Uber 072515 SF**POOL**" validate:"required"`
	// Original merchant name is immutable. It can only be set when the transaction is created. This is used to preserve
	// some data about the original transaction and is primarily used by the Plaid integration. It is not required for
	// manually created transactions.
	OriginalMerchantName string `json:"originalMerchantName" example:"Uber"`
	// Original categories from when the transaction was created by the user, or imported from Plaid. this field cannot
	// be changed after the transaction has been created.
	OriginalCategories []string `json:"originalCategories" example:"Restaurants,Fast Food" extensions:"x-nullable"`
}

type TransactionResponse struct {
	NewTransactionRequest
	UpdateTransactionRequest
	// The unique Id for the transaction within monetr. This is globally unique.
	TransactionId uint64 `json:"transactionId" example:"58732" validate:"required"`
	// SpendingAmount is the amount deducted from the expense this transaction was spent from. This is used when a
	// transaction is more than the expense currently has allocated. If the transaction were to be deleted or changed we
	// want to make sure we return the correct amount to the expense.
	SpendingAmount *int64 `json:"spendingAmount,omitempty" example:"800" extensions:"x-nullable"`

	// Specifies the timestamp that the transaction was created within monetr and is used to help sort transactions as
	// the transaction `date` does not contain a time of day.
	CreatedAt time.Time `json:"createdAt" example:"2021-04-15T00:00:00-05:00"`
}

type TransactionUpdateResponse struct {
	// The resulting transaction object with any calculated changes applied.
	Transaction TransactionResponse `json:"transaction"`
	// Will contain up to two spending objects. Includes the spending objects that were updated if the `spendingId`
	// field of the transaction was changed in the request.
	Spending []SpendingResponse `json:"spending,omitempty"`
	// The new balances for the bank account that the transaction belongs to. This is returned so that the UI can easily
	// see the affects of updating a transaction's spending object right away.
	Balance BalanceResponse `json:"balance"`
}
