cache_path: ./build/license.cache

sources:
  npm: true
  go: true

go:
  GOPATH: ~/go

npm:
  production_only: true

pnpm:
  production_only: true

apps:
  - name: monetr-API
    source_path: server/cmd
  - name: monetr-UI
    source_path: .

allowed:
  - 0bsd
  - apache-2.0
  - bsd
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - mit
  - mpl-2.0
  - ofl-1.1
  - unlicense

licensee:
  # https://github.com/licensee/licensee/blob/master/docs/customizing.md#adjusting-the-confidence-threshold
  confidence_threshold: 90

reviewed:
  go: []
  npm: []

ignored:
  npm: # Silence warning about missing license. Its not missing.
    - "@esbuild/*"
    - "@img/sharp-*" # https://github.com/lovell/sharp?tab=Apache-2.0-1-ov-file#readme
    - "@napi-rs/simple-git-*" # MIT License https://github.com/Brooooooklyn/simple-git/blob/main/LICENSE
    - "@next/swc-*"
    - "@oven/bun-*" # https://github.com/oven-sh/bun/blob/main/LICENSE.md
    - "@parcel/watcher-*" # https://github.com/parcel-bundler/watcher?tab=MIT-1-ov-file#readme
    - "@rspack/*"
    - "@swc/*"
    - "fsevents"  # MIT License https://github.com/fsevents/fsevents/blob/master/LICENSE
    - "sass-embedded-*" # MIT License https://github.com/sass/embedded-host-node/blob/main/LICENSE

