
default:
	$(info "This makefile is meant to be used in CI.")

apply-schema-ci:
ifndef GITHUB_WORKSPACE
	$(warning "GITHUB_WORKSPACE is not defined, are you running in CI?")
	$(eval GITHUB_WORKSPACE = $(PWD))
endif
	$(GITHUB_WORKSPACE)/bin/monetr database migrate -d $(POSTGRES_DB) -U $(POSTGRES_USER) -H $(POSTGRES_HOST)