
default-deploy:
	$(error Please run a specific target)

ifndef ENV_LOWER
$(error Envrionment not properly specicfied)
endif

BUCKET_NAME = gs://monetr-$(ENV_LOWER)
BUILD_DIR = $(PWD)/build

ifneq ($(ENVIRONMENT), "Local")
deploy:
	cp $(PWD)/config.$(ENV_LOWER).json $(BUILD_DIR)/config.json
	gsutil cp -e -r -z js $(BUILD_DIR)/* $(BUCKET_NAME)
else
deploy:
	echo "Work in progress"
endif
