
default:
	$(info "This makefile is meant to be used in CI.")

apply-schema-ci:
ifndef CI_PROJECT_DIR
	$(warning "CI_PROJECT_DIR is not defined, are you running in CI?")
	$(eval CI_PROJECT_DIR := $(PWD))
endif
	$(CI_PROJECT_DIR)/bin/monetr database migrate -d $(POSTGRES_DB) -U $(POSTGRES_USER) -H $(POSTGRES_HOST)
