packages:
  - docs
  - interface
  - emails
allowBuilds:
  '@swc/core': false
  core-js: false

saveExact: true
savePrefix: ""

preferFrozenLockfile: true

trustPolicy: no-downgrade
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@monetr/*'
