ALTER TABLE "accounts" ALTER COLUMN "subscription_active_until" TYPE TIMESTAMP WITHOUT TIME ZONE USING "subscription_active_until" AT TIME ZONE 'UTC';
ALTER TABLE "accounts" ALTER COLUMN "stripe_webhook_latest_timestamp" TYPE TIMESTAMP WITHOUT TIME ZONE USING "stripe_webhook_latest_timestamp" AT TIME ZONE 'UTC';
ALTER TABLE "accounts" ALTER COLUMN "trial_ends_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "trial_ends_at" AT TIME ZONE 'UTC';
ALTER TABLE "accounts" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "accounts" ALTER COLUMN "trial_expiry_notification_sent_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "trial_expiry_notification_sent_at" AT TIME ZONE 'UTC';

ALTER TABLE "bank_accounts" ALTER COLUMN "last_updated" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_updated" AT TIME ZONE 'UTC';
ALTER TABLE "bank_accounts" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "bank_accounts" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "bank_accounts" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';

ALTER TABLE "betas" ALTER COLUMN "expires_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "expires_at" AT TIME ZONE 'UTC';

ALTER TABLE "cron_jobs" ALTER COLUMN "last_run_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_run_at" AT TIME ZONE 'UTC';
ALTER TABLE "cron_jobs" ALTER COLUMN "next_run_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "next_run_at" AT TIME ZONE 'UTC';

ALTER TABLE "files" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "files" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';
ALTER TABLE "files" ALTER COLUMN "reconciled_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "reconciled_at" AT TIME ZONE 'UTC';
ALTER TABLE "files" ALTER COLUMN "expires_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "expires_at" AT TIME ZONE 'UTC';

ALTER TABLE "funding_schedules" ALTER COLUMN "last_recurrence" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_recurrence" AT TIME ZONE 'UTC';
ALTER TABLE "funding_schedules" ALTER COLUMN "next_recurrence" TYPE TIMESTAMP WITHOUT TIME ZONE USING "next_recurrence" AT TIME ZONE 'UTC';
ALTER TABLE "funding_schedules" ALTER COLUMN "next_recurrence_original" TYPE TIMESTAMP WITHOUT TIME ZONE USING "next_recurrence_original" AT TIME ZONE 'UTC';

ALTER TABLE "jobs" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "jobs" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "jobs" ALTER COLUMN "started_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "started_at" AT TIME ZONE 'UTC';
ALTER TABLE "jobs" ALTER COLUMN "completed_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "completed_at" AT TIME ZONE 'UTC';

ALTER TABLE "links" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "links" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "links" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';


ALTER TABLE "logins" ALTER COLUMN "totp_enabled_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "totp_enabled_at" AT TIME ZONE 'UTC';
ALTER TABLE "logins" ALTER COLUMN "email_verified_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "email_verified_at" AT TIME ZONE 'UTC';
ALTER TABLE "logins" ALTER COLUMN "password_reset_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "password_reset_at" AT TIME ZONE 'UTC';

ALTER TABLE "plaid_bank_accounts" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';

ALTER TABLE "plaid_links" ALTER COLUMN "expiration_date" TYPE TIMESTAMP WITHOUT TIME ZONE USING "expiration_date" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "last_manual_sync" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_manual_sync" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "last_successful_update" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_successful_update" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "last_attempted_update" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_attempted_update" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_links" ALTER COLUMN "last_account_sync" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_account_sync" AT TIME ZONE 'UTC';

ALTER TABLE "plaid_syncs" ALTER COLUMN "timestamp" TYPE TIMESTAMP WITHOUT TIME ZONE USING "timestamp" AT TIME ZONE 'UTC';

ALTER TABLE "plaid_transactions" ALTER COLUMN "date" TYPE TIMESTAMP WITHOUT TIME ZONE USING "date" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_transactions" ALTER COLUMN "authorized_date" TYPE TIMESTAMP WITHOUT TIME ZONE USING "authorized_date" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_transactions" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "plaid_transactions" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';

ALTER TABLE "secrets" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "secrets" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';

ALTER TABLE "spending" ALTER COLUMN "last_recurrence" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_recurrence" AT TIME ZONE 'UTC';
ALTER TABLE "spending" ALTER COLUMN "next_recurrence" TYPE TIMESTAMP WITHOUT TIME ZONE USING "next_recurrence" AT TIME ZONE 'UTC';
ALTER TABLE "spending" ALTER COLUMN "last_spent_from" TYPE TIMESTAMP WITHOUT TIME ZONE USING "last_spent_from" AT TIME ZONE 'UTC';
ALTER TABLE "spending" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';

ALTER TABLE "transaction_clusters" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';

ALTER TABLE "transaction_uploads" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "transaction_uploads" ALTER COLUMN "processed_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "processed_at" AT TIME ZONE 'UTC';
ALTER TABLE "transaction_uploads" ALTER COLUMN "completed_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "completed_at" AT TIME ZONE 'UTC';

ALTER TABLE "transactions" ALTER COLUMN "date" TYPE TIMESTAMP WITHOUT TIME ZONE USING "date" AT TIME ZONE 'UTC';
ALTER TABLE "transactions" ALTER COLUMN "created_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "transactions" ALTER COLUMN "deleted_at" TYPE TIMESTAMP WITHOUT TIME ZONE USING "deleted_at" AT TIME ZONE 'UTC';
