// Code generated by "stringer -type=LinkStatus -output=link.strings.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LinkStatusUnknown-0]
	_ = x[LinkStatusPending-1]
	_ = x[LinkStatusSetup-2]
	_ = x[LinkStatusError-3]
	_ = x[LinkStatusPendingExpiration-4]
	_ = x[LinkStatusRevoked-5]
}

const _LinkStatus_name = "LinkStatusUnknownLinkStatusPendingLinkStatusSetupLinkStatusErrorLinkStatusPendingExpirationLinkStatusRevoked"

var _LinkStatus_index = [...]uint8{0, 17, 34, 49, 64, 91, 108}

func (i LinkStatus) String() string {
	if i >= LinkStatus(len(_LinkStatus_index)-1) {
		return "LinkStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkStatus_name[_LinkStatus_index[i]:_LinkStatus_index[i+1]]
}
