// Code generated by "stringer -type=LinkType -output=link_type.strings.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownLinkType-0]
	_ = x[PlaidLinkType-1]
	_ = x[ManualLinkType-2]
}

const _LinkType_name = "UnknownLinkTypePlaidLinkTypeManualLinkType"

var _LinkType_index = [...]uint8{0, 15, 28, 42}

func (i LinkType) String() string {
	if i >= LinkType(len(_LinkType_index)-1) {
		return "LinkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkType_name[_LinkType_index[i]:_LinkType_index[i+1]]
}
