// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -package=mockgen -destination=../../internal/mockgen/lunch_flow_client.go LunchFlowClient
//

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	reflect "reflect"

	lunch_flow "github.com/monetr/monetr/server/datasources/lunch_flow"
	gomock "go.uber.org/mock/gomock"
)

// MockLunchFlowClient is a mock of LunchFlowClient interface.
type MockLunchFlowClient struct {
	ctrl     *gomock.Controller
	recorder *MockLunchFlowClientMockRecorder
	isgomock struct{}
}

// MockLunchFlowClientMockRecorder is the mock recorder for MockLunchFlowClient.
type MockLunchFlowClientMockRecorder struct {
	mock *MockLunchFlowClient
}

// NewMockLunchFlowClient creates a new mock instance.
func NewMockLunchFlowClient(ctrl *gomock.Controller) *MockLunchFlowClient {
	mock := &MockLunchFlowClient{ctrl: ctrl}
	mock.recorder = &MockLunchFlowClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLunchFlowClient) EXPECT() *MockLunchFlowClientMockRecorder {
	return m.recorder
}

// GetAccounts mocks base method.
func (m *MockLunchFlowClient) GetAccounts(ctx context.Context) ([]lunch_flow.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx)
	ret0, _ := ret[0].([]lunch_flow.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockLunchFlowClientMockRecorder) GetAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockLunchFlowClient)(nil).GetAccounts), ctx)
}

// GetBalance mocks base method.
func (m *MockLunchFlowClient) GetBalance(ctx context.Context, accountId lunch_flow.AccountId) (*lunch_flow.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountId)
	ret0, _ := ret[0].(*lunch_flow.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLunchFlowClientMockRecorder) GetBalance(ctx, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLunchFlowClient)(nil).GetBalance), ctx, accountId)
}

// GetTransactions mocks base method.
func (m *MockLunchFlowClient) GetTransactions(ctx context.Context, accountId lunch_flow.AccountId) ([]lunch_flow.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, accountId)
	ret0, _ := ret[0].([]lunch_flow.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockLunchFlowClientMockRecorder) GetTransactions(ctx, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockLunchFlowClient)(nil).GetTransactions), ctx, accountId)
}
