// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -source=queue.go -package=mockgen -destination=../internal/mockgen/queue.go Processor
//

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	slog "log/slog"
	reflect "reflect"
	time "time"

	clock "github.com/benbjohnson/clock"
	pg "github.com/go-pg/pg/v10"
	billing "github.com/monetr/monetr/server/billing"
	communication "github.com/monetr/monetr/server/communication"
	models "github.com/monetr/monetr/server/models"
	platypus "github.com/monetr/monetr/server/platypus"
	pubsub "github.com/monetr/monetr/server/pubsub"
	queue "github.com/monetr/monetr/server/queue"
	secrets "github.com/monetr/monetr/server/secrets"
	storage "github.com/monetr/monetr/server/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Billing mocks base method.
func (m *MockContext) Billing() billing.Billing {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Billing")
	ret0, _ := ret[0].(billing.Billing)
	return ret0
}

// Billing indicates an expected call of Billing.
func (mr *MockContextMockRecorder) Billing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Billing", reflect.TypeOf((*MockContext)(nil).Billing))
}

// Clock mocks base method.
func (m *MockContext) Clock() clock.Clock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clock")
	ret0, _ := ret[0].(clock.Clock)
	return ret0
}

// Clock indicates an expected call of Clock.
func (mr *MockContextMockRecorder) Clock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clock", reflect.TypeOf((*MockContext)(nil).Clock))
}

// DB mocks base method.
func (m *MockContext) DB() pg.DBI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(pg.DBI)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockContextMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockContext)(nil).DB))
}

// Deadline mocks base method.
func (m *MockContext) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockContextMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockContext)(nil).Deadline))
}

// Done mocks base method.
func (m *MockContext) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockContextMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockContext)(nil).Done))
}

// Email mocks base method.
func (m *MockContext) Email() communication.EmailCommunication {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email")
	ret0, _ := ret[0].(communication.EmailCommunication)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockContextMockRecorder) Email() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockContext)(nil).Email))
}

// Enqueuer mocks base method.
func (m *MockContext) Enqueuer() queue.Enqueuer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueuer")
	ret0, _ := ret[0].(queue.Enqueuer)
	return ret0
}

// Enqueuer indicates an expected call of Enqueuer.
func (mr *MockContextMockRecorder) Enqueuer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueuer", reflect.TypeOf((*MockContext)(nil).Enqueuer))
}

// Err mocks base method.
func (m *MockContext) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockContextMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockContext)(nil).Err))
}

// Job mocks base method.
func (m *MockContext) Job() models.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Job")
	ret0, _ := ret[0].(models.Job)
	return ret0
}

// Job indicates an expected call of Job.
func (mr *MockContextMockRecorder) Job() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Job", reflect.TypeOf((*MockContext)(nil).Job))
}

// KMS mocks base method.
func (m *MockContext) KMS() secrets.KeyManagement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KMS")
	ret0, _ := ret[0].(secrets.KeyManagement)
	return ret0
}

// KMS indicates an expected call of KMS.
func (mr *MockContextMockRecorder) KMS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KMS", reflect.TypeOf((*MockContext)(nil).KMS))
}

// Log mocks base method.
func (m *MockContext) Log() *slog.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(*slog.Logger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockContextMockRecorder) Log() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockContext)(nil).Log))
}

// Platypus mocks base method.
func (m *MockContext) Platypus() platypus.Platypus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platypus")
	ret0, _ := ret[0].(platypus.Platypus)
	return ret0
}

// Platypus indicates an expected call of Platypus.
func (mr *MockContextMockRecorder) Platypus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platypus", reflect.TypeOf((*MockContext)(nil).Platypus))
}

// Publisher mocks base method.
func (m *MockContext) Publisher() pubsub.Publisher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publisher")
	ret0, _ := ret[0].(pubsub.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher.
func (mr *MockContextMockRecorder) Publisher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publisher", reflect.TypeOf((*MockContext)(nil).Publisher))
}

// RunInTransaction mocks base method.
func (m *MockContext) RunInTransaction(ctx context.Context, callback func(queue.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTransaction", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTransaction indicates an expected call of RunInTransaction.
func (mr *MockContextMockRecorder) RunInTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTransaction", reflect.TypeOf((*MockContext)(nil).RunInTransaction), ctx, callback)
}

// Storage mocks base method.
func (m *MockContext) Storage() storage.Storage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage")
	ret0, _ := ret[0].(storage.Storage)
	return ret0
}

// Storage indicates an expected call of Storage.
func (mr *MockContextMockRecorder) Storage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockContext)(nil).Storage))
}

// Value mocks base method.
func (m *MockContext) Value(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockContextMockRecorder) Value(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockContext)(nil).Value), key)
}

// MockEnqueuer is a mock of Enqueuer interface.
type MockEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockEnqueuerMockRecorder
	isgomock struct{}
}

// MockEnqueuerMockRecorder is the mock recorder for MockEnqueuer.
type MockEnqueuerMockRecorder struct {
	mock *MockEnqueuer
}

// NewMockEnqueuer creates a new mock instance.
func NewMockEnqueuer(ctrl *gomock.Controller) *MockEnqueuer {
	mock := &MockEnqueuer{ctrl: ctrl}
	mock.recorder = &MockEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnqueuer) EXPECT() *MockEnqueuerMockRecorder {
	return m.recorder
}

// EnqueueAt mocks base method.
func (m *MockEnqueuer) EnqueueAt(ctx context.Context, arg1 string, at time.Time, args any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueAt", ctx, arg1, at, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueAt indicates an expected call of EnqueueAt.
func (mr *MockEnqueuerMockRecorder) EnqueueAt(ctx, arg1, at, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueAt", reflect.TypeOf((*MockEnqueuer)(nil).EnqueueAt), ctx, arg1, at, args)
}

// WithTransaction mocks base method.
func (m *MockEnqueuer) WithTransaction(db pg.DBI) queue.Enqueuer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", db)
	ret0, _ := ret[0].(queue.Enqueuer)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockEnqueuerMockRecorder) WithTransaction(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockEnqueuer)(nil).WithTransaction), db)
}

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProcessor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProcessorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProcessor)(nil).Close))
}

// EnqueueAt mocks base method.
func (m *MockProcessor) EnqueueAt(ctx context.Context, arg1 string, at time.Time, args any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueAt", ctx, arg1, at, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueAt indicates an expected call of EnqueueAt.
func (mr *MockProcessorMockRecorder) EnqueueAt(ctx, arg1, at, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueAt", reflect.TypeOf((*MockProcessor)(nil).EnqueueAt), ctx, arg1, at, args)
}

// Register mocks base method.
func (m *MockProcessor) Register(ctx context.Context, arg1 string, job queue.InternalJobWrapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, arg1, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockProcessorMockRecorder) Register(ctx, arg1, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockProcessor)(nil).Register), ctx, arg1, job)
}

// RegisterCron mocks base method.
func (m *MockProcessor) RegisterCron(ctx context.Context, arg1, schedule string, job queue.InternalJobWrapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCron", ctx, arg1, schedule, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCron indicates an expected call of RegisterCron.
func (mr *MockProcessorMockRecorder) RegisterCron(ctx, arg1, schedule, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCron", reflect.TypeOf((*MockProcessor)(nil).RegisterCron), ctx, arg1, schedule, job)
}

// Start mocks base method.
func (m *MockProcessor) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockProcessorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProcessor)(nil).Start))
}

// WithTransaction mocks base method.
func (m *MockProcessor) WithTransaction(db pg.DBI) queue.Enqueuer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", db)
	ret0, _ := ret[0].(queue.Enqueuer)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockProcessorMockRecorder) WithTransaction(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockProcessor)(nil).WithTransaction), db)
}
