package schema

import (
	"fmt"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/monetr/monetr/server/models"
)

// ID creates a jsonschema object representing the ID of that object. This can
// then be used to validate ID strings for any object of that type and will
// reject IDs for other object types.
func ID[T models.Identifiable](id string) *jsonschema.Schema {
	inst := *new(T)
	name := strings.ReplaceAll("models.", fmt.Sprintf("%T", inst), "")
	return &jsonschema.Schema{
		ID:          id,
		Comment:     fmt.Sprintf("The unique identifier for %s objects", name),
		Description: fmt.Sprintf("The unique identifier for %s objects", name),
		Type:        "string",
		// This regex matches ULID strings that are lower case based on the spec.
		// This includes the monetr string prefix that is generated by the specified
		// object type.
		Pattern: fmt.Sprintf(`^%s_[0-7][0-9a-hjkmnp-tv-z]{25}$`, inst.IdentityPrefix()),
		Examples: []any{
			fmt.Sprintf("%s_01kgaza3ckr5s0n16banqx5t9x", inst.IdentityPrefix()),
		},
		ReadOnly: true,
	}
}

