services:
  documentation:
    image: ${MKDOCS_IMAGE:-squidfunk/mkdocs-material:9.2.8}
    user: "${UID:-0}:${GID:-0}"
    restart: always # If something goes wrong just restart the container, this is for development only.
    working_dir: /build
    entrypoint: sh
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8000/documentation", "-O", "/dev/null"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 30s
    command:
      - /build/compose/docs-entrypoint.sh
    volumes:
      - ./:/build
    ports:
      - 8000:8000
