// Code generated by "stringer -type=TellerBankAccountStatus -output=teller_bank_account.strings.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TellerBankAccountStatusUnknown-0]
	_ = x[TellerBankAccountStatusOpen-1]
	_ = x[TellerBankAccountStatusClosed-2]
}

const _TellerBankAccountStatus_name = "TellerBankAccountStatusUnknownTellerBankAccountStatusOpenTellerBankAccountStatusClosed"

var _TellerBankAccountStatus_index = [...]uint8{0, 30, 57, 86}

func (i TellerBankAccountStatus) String() string {
	if i >= TellerBankAccountStatus(len(_TellerBankAccountStatus_index)-1) {
		return "TellerBankAccountStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TellerBankAccountStatus_name[_TellerBankAccountStatus_index[i]:_TellerBankAccountStatus_index[i+1]]
}
