export const FETCH_BANK_ACCOUNTS_REQUEST = 'FETCH_BANK_ACCOUNTS_REQUEST';
export const FETCH_BANK_ACCOUNT_FAILURE = 'FETCH_BANK_ACCOUNT_FAILURE';
export const FETCH_BANK_ACCOUNT_SUCCESS = 'FETCH_BANK_ACCOUNT_SUCCESS';
