{{ if .Values.api.includeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
  {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.api.email.verification.tokenSecret }}
  MONETR_EMAIL_VERIFICATION_TOKEN_SECRET: {{ quote .Values.api.email.verification.tokenSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.email.forgotPassword.tokenSecret }}
  MONETR_EMAIL_FORGOT_PASSWORD_TOKEN_SECRET: {{ quote .Values.api.email.forgotPassword.tokenSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.email.smtp.password }}
  MONETR_EMAIL_SMTP_PASSWORD: {{ quote .Values.api.email.smtp.password | b64enc | quote }}
  {{- end }}
  MONETR_JWT_LOGIN_SECRET: {{ default "" .Values.api.jwt.loginJwtSecret | b64enc | quote }}
  MONETR_JWT_REGISTRATION_SECRET: {{ default "" .Values.api.jwt.registrationJwtSecret | b64enc | quote }}

  {{- if .Values.api.postgreSql.username }}
  MONETR_PG_USERNAME: {{ default "" .Values.api.postgreSql.username | b64enc | quote }}
  {{- end }}

  {{- if .Values.api.sentry.enabled }}
  MONETR_SENTRY_DSN: {{ default "" .Values.api.sentry.dsn | b64enc | quote }}
  MONETR_SENTRY_EXTERNAL_DSN: {{ default "" .Values.api.sentry.externalDsn | b64enc | quote }}
  {{- end }}

  {{- if .Values.api.postgreSql.password }}
  MONETR_PG_PASSWORD: {{ default "" .Values.api.postgreSql.password | b64enc | quote }}
  {{- end }}

  MONETR_CAPTCHA_PUBLIC_KEY: {{ default "" .Values.api.reCaptcha.publicKey | b64enc | quote }}
  MONETR_CAPTCHA_PRIVATE_KEY: {{ default "" .Values.api.reCaptcha.privateKey | b64enc | quote }}
  MONETR_PLAID_CLIENT_ID: {{ default "" .Values.api.plaid.clientId | b64enc | quote }}
  MONETR_PLAID_CLIENT_SECRET: {{ default "" .Values.api.plaid.clientSecret | b64enc | quote }}
  MONETR_STRIPE_API_KEY: {{ default "" .Values.api.stripe.apiKey | b64enc | quote }}
  MONETR_STRIPE_PUBLIC_KEY: {{ default "" .Values.api.stripe.publicKey | b64enc | quote }}
  MONETR_STRIPE_WEBHOOK_SECRET: {{ default "" .Values.api.stripe.webhookSecret | b64enc | quote }}
  {{ end }}