{{ if .Values.api.includeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
  {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  HARDER_JWT_LOGIN_SECRET: {{ default "" .Values.api.jwt.loginJwtSecret | b64enc | quote }}
  HARDER_JWT_REGISTRATION_SECRET: {{ default "" .Values.api.jwt.registrationJwtSecret | b64enc | quote }}

  {{- if .Values.api.postgreSql.username }}
  HARDER_PG_USERNAME: {{ default "" .Values.api.postgreSql.username | b64enc | quote }}
  {{- end }}

  {{- if .Values.api.postgreSql.password }}
  HARDER_PG_PASSWORD: {{ default "" .Values.api.postgreSql.password | b64enc | quote }}
  {{- end }}

  HARDER_CAPTCHA_PUBLIC_KEY: {{ default "" .Values.api.reCaptcha.publicKey | b64enc | quote }}
  HARDER_CAPTCHA_PRIVATE_KEY: {{ default "" .Values.api.reCaptcha.privateKey | b64enc | quote }}
  HARDER_PLAID_CLIENT_ID: {{ default "" .Values.api.plaid.clientId | b64enc | quote }}
  HARDER_PLAID_CLIENT_SECRET: {{ default "" .Values.api.plaid.clientSecret | b64enc | quote }}

{{ end }}