// Code generated by "stringer -type=DatabaseEngine -output=database.strings.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PostgreSQLDatabaseEngine-1]
	_ = x[MySQLDatabaseEngine-2]
	_ = x[SQLiteDatabaseEngine-3]
}

const _DatabaseEngine_name = "PostgreSQLDatabaseEngineMySQLDatabaseEngineSQLiteDatabaseEngine"

var _DatabaseEngine_index = [...]uint8{0, 24, 43, 63}

func (i DatabaseEngine) String() string {
	i -= 1
	if i >= DatabaseEngine(len(_DatabaseEngine_index)-1) {
		return "DatabaseEngine(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DatabaseEngine_name[_DatabaseEngine_index[i]:_DatabaseEngine_index[i+1]]
}
