// Code generated by "stringer -type=BasicDataType -output=basic_data_types.strings.go"; DO NOT EDIT.

package migrations

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SmallInteger-0]
	_ = x[Integer-1]
	_ = x[BigInteger-2]
	_ = x[Boolean-3]
	_ = x[Blob-4]
	_ = x[Date-5]
	_ = x[Timestamp-6]
	_ = x[JSON-7]
}

const _BasicDataType_name = "TinyIntegerIntegerBigIntegerBooleanBlobDateTimestampJSON"

var _BasicDataType_index = [...]uint8{0, 11, 18, 28, 35, 39, 43, 52, 56}

func (i BasicDataType) String() string {
	if i >= BasicDataType(len(_BasicDataType_index)-1) {
		return "BasicDataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BasicDataType_name[_BasicDataType_index[i]:_BasicDataType_index[i+1]]
}
